const User = require('../models/user')


// The await keyword can only be used inside an async function
// async before a function makes the function return a promise
// await makes the function pause the execution and wait for a resolved promise before it continues
// It restricts the db can move forward only if it receives a brand new user
exports.create = async (req, res) => {

    const {name:name, email:email, password:password} = req.body

    /**
     * prevent the duplicate user by finding user with same email: same email means same user
     , and different email mail different users
     */ 
    const oldUser = await User.findOne({ email });
    if (oldUser) return res.status(401).json({ error:" This email is already in use! "})

    // create a brand new user with name, email , and password
    const newUser = new User({name, email, password})
    // save the brand new user in mongodb
    await newUser.save()


    // get the resp json data request by the user with ID generated by mongodb
    res.status(201).json({user:newUser})
}

