const movieInfo = {
    title: "some title",
    storyLine: "little bit about the movie",
    director: "123456",
    releaseDate: "06-17-2023",
    status:"private",
    type:"Movie",
    genres:["Sci-fi","Action"],
    tags:["action","movie","hollywood"],
    cast:[{id:"abc1234ss", roleAs:"John Die", leadActor:true}],
    writers:["name1","name2"],
    poster:File,
    trailer:{url:"https://", public_id:"fkasdfi456"},
    language:"English ",
  };